//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Examen
    {
        public int fi_idExamen { get; set; }
        public string fc_Nombre { get; set; }
        public string fc_Descripcion { get; set; }
        public int fb_Estatus { get; set; }
        public Nullable<System.DateTime> fd_falta { get; set; }
        public Nullable<System.DateTime> fd_fechaModificacion { get; set; }
    }
}
